language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
# adding environnment variables
env:
  global:
    - HVAC_HOST = "https://log680.vincentboivin.ca"
    - HVAC_TOKEN = "89103df59ad0cda23c2f"
# command to run tests
script:
  - python test/test_main.py
