language: python
os: win32
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - unittest
