language: python
python:
  - "3.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
# adding environnment variables
env:
  global:
    - HVAC_HOST = "https://log680.vincentboivin.ca"
    - HVAC_TOKEN = "89103df59ad0cda23c2f"
# command to run tests
script:
  - python test/test_main.py
