language: python
python:
  - "3.7"
services:
  - docker
# Build docker image and test
before_install:
  - docker build -t labo2:latest .
  - docker ps -a
  - docker run labo2:latest python3 test/test_main.py
# command to run tests
#script:
  - python test/test_main.py
# Push the docker image on main
deploy:
  - docker login -u "$DOCKER_USERNAME" --password  "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/log680-lab2:latest
  on:
    branch: main

# command to install dependencies
#install:
#  - pip install -r requirements.txt
# adding environnment variables
env:
  global:
    - HVAC_HOST=https://log680.vincentboivin.ca 
    - HVAC_TOKEN=89103df59ad0cda23c2f

